### ISSUE TITLE
What is braket_form?

### ISSUE THREAD

**Issue by ZlinTsai** [kaihsin/Cytnx#1]
Hi, Kai-Hsin

I know braket in physics, but i get two different diagram with/without braket_form when I use print_diagram() .

![image](https://user-images.githubusercontent.com/37646878/62379430-87787700-b579-11e9-9fe7-09bf1e183154.png)

So, my question is that: What is braket_form, and its use?

source code:

#include <iostream>
#include "cytnx.hpp"

using namespace std;

int main(int argc, char *argv[])
{
    cytnx::Bond bd_1(2, cytnx::BD_BRA);
    cytnx::Bond bd_2(3, cytnx::BD_BRA);
    cytnx::Bond bd_3(5, cytnx::BD_KET);

    vector<cytnx::Bond> bds = {bd_1, bd_2, bd_3}; 

    cytnx::UniTensor B;
    B.Init(bds, {}, 2);
    //cout << B << endl;
    B.print_diagram();

    cout << "**********************" << endl;

    cytnx::Tensor tn = cytnx::arange(30).reshape({2, 3, 5});
    //cout << tn << endl;
    cytnx::UniTensor C; 
    C.Init(tn, 2);
    C.print_diagram();

    return 0;
}

**Comment by kaihsin** [comment]
The UniTensor can be tagged or untagged base on the property of Bonds that is pass-in when initialize the UniTensor. 

    If the Bonds of UniTensor is tag with BD_BRA or BD_KET, we called it tagged UniTensor. On the other hand, if the Bonds of UniTensor are all BD_REG, the UniTensor is un-tagged, which is nothing but a nornal Tensor with additional enhance feature such as "labels", "contract" etc. 
**This is a little bit different from uni10. In uni10, no BD_REG is provided.**

The important concept of difference are:
1. The BD_REG Bonds (as well as un-tagged UniTensor) are specifically handy in the case where the Network algo. are without symmetry, and the BRA/KET is not so important ( as in uni10 sometimes we just let all the bond to be BD_BRA which is redundant when it comes to the real implementation) . 

2. Bonds from 2 untagged UniTensors can contract as long as the label are match.  HOWEVER, if the Bonds are tagged with BD_BRA / BD_KET, we explicitly defines that the Bond should be in physical Bra/Ket space. Thus, When contract 2 UniTensor, BD_BRA Bond can ONLY contract with BD_KET Bond, as the physical bra-ket operation.   

3. the `Rowrank` defines the Bonds in left / right. For example, if the UniTensor is rank-5, and Rowrank=2. The first two Bonds will appears in left, and the other 3 Bonds will appears in right. 

4. From 3., Since the BD_KET should physically appears on the left side of UniTensor (as ket should live on the col space), and BD_BRA should physically appears on the right side of UniTensor( as bra should live on the row space). **if one permute a BD_KET Bond to the right ( or BD_BRA to the left), it cause the mismatch We called this status as braket_form=False** and the Bond that is mismatch will have a star symbol indicating the mismatch.   

--------------------------------------------------------------------
Now, lets look at your example. 

In your UniTensor `B`, you initialize with tagged Bonds  `bd_1` (BD_BRA),  `bd_2` (BD_BRA) and `bd_3` (BD_KET). So UniTensor `B` is tagged Tensor. 

In your UniTensor `C`, you initialize a UniTensor from a Tensor `tn`, so the default behavior for this is that the UniTensor will always be **untagged** when initialize from a Tensor. The is equivalent as:

```
cytnx::UniTensor C2({ Bond(2), Bond(3), Bond(5) },{},2); 
C2.put_block(tn);
```
