### ISSUE TITLE
Memory alignment and openMP

### ISSUE THREAD

**Issue by j9263178** [kaihsin/Cytnx#101]
To figure out whether the false sharing or other bad things happened, we should test if the memory alignment of the input tensor will affect the performance of multithread Trace().

**Comment by jeffry1829** [comment]
The multithread problem now is Memory Bound and Core Bound. Which can be seen from here:
![image](https://user-images.githubusercontent.com/6897769/174965195-5c896352-a6ec-44de-9d86-322e2158b2e8.png)
![image](https://user-images.githubusercontent.com/6897769/174967040-5d0ee034-872b-4ca7-9a6b-3020f160269e.png)

Also, the single thread profiling is here:
![image](https://user-images.githubusercontent.com/6897769/174966100-b032f23e-9641-49ee-86ad-1a76e9a931bf.png)
![image](https://user-images.githubusercontent.com/6897769/174967085-b5ed667f-7add-4851-8713-298ce12ed246.png)

(The elapse time doesn't matter, since I may change input data size)

**Comment by jeffry1829** [comment]
Profiling indicates that Trace wrap on mkl is ~22x faster than single thread implementation.
