### ISSUE TITLE
DMRG example

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#110]
I tried to run the DMRG code in the example folder and got errors. Here are the error message:

For dmrg_two_sites.py:
```
Traceback (most recent call last):
  File "dmrg_two_sites.py", line 62, in <module>
    M[0,0] = M[3,3] = eye
RuntimeError: 
# Cytnx error occur at void cytnx::Tensor_impl::set(const std::vector<cytnx::Accessor>&, const boost::intrusive_ptr<cytnx::Tensor_impl>&)
# error: [ERROR][Tensor.set_elems]inconsistent shape
# file : /home/travis/miniconda/envs/test-environment/conda-bld/cytnx_1614926727399/work/src/Tensor.cpp (645)
```

For dmrg_two_sites_U1.py:
```
Traceback (most recent call last):
  File "dmrg_two_sites_U1.py", line 78, in <module>
    M = cytnx.UniTensor([bd_inner,bd_inner.redirect(),bd_phys, bd_phys.redirect()],rowrank=2)
AttributeError: 'cytnx.cytnx.Bond' object has no attribute 'redirect'
```

**Comment by jeffry1829** [comment]
Hi, you may need to use latest version, and change parameter 2 to initialization of UniTensor. Since in old version, the parameter 2 of UniTensor initialization is rowrank, however, in current version, the second parameter is "is_diag" while the third parameter is rowrank.

For example, use this https://gist.github.com/jeffry1829/f871c1b18c363176fba22a694e47ed06

However, I can't reproduce these errors

**Comment by chiamin** [comment]
We have "solved" the error for the reason I don't understand...., but I couldn't reproduce the error, so I will close the issue and create a new one if I found it again.
