### ISSUE TITLE
Conda install error

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#111]
I got several errors in installing Cytnx by Conda. I attached all the error messages in the bottom.

The first error is about Numpy not found. I tried to solve the issue by `conda install numpy`. Seems working fine.

Then I got the second error about Cytnx not found. I tried to solve it by `conda install cytnx`; didn't work.

My conda version is 4.10.3.

Error messages:
[error1.txt](https://github.com/kaihsin/Cytnx/files/9227690/error1.txt)
[error2.txt](https://github.com/kaihsin/Cytnx/files/9227691/error2.txt)
[error3.txt](https://github.com/kaihsin/Cytnx/files/9227692/error3.txt)

**Comment by jeffry1829** [comment]
Hi! for numpy not found. It seems like you didn't install cytnx, thus those dependencies(include numpy) won't be avaliable.
And the error3.txt is empty, I guess you may need to use `conda install -c kaihsinwu cytnx` to specify which channel did you want to find package cytnx.

By the way, you may want to use `mamba`, since it's faster, and more importantly, it shows better error message(while conda will produce many nonsense error. For instance, glibc version too old error)
This is an brief installation guide: https://www.cnblogs.com/feffery/p/13232119.html

Thanks!
