### ISSUE TITLE
Error in Lapacke 'dstev' during the Lanczos_Gnd_Ut

### ISSUE THREAD

**Issue by j9263178** [kaihsin/Cytnx#134]
When running `Lanczos_Gnd` and `Lanczos_Gnd_Ut` in DMRG one may encounter:
  
 `Error in Lapack function 'dstev' : Lapack INFO = -4`  
  
This means that the fourth argument (subdiagonal of the tridiagonal matrix?) had an illegal value, this may appear when the starting vector in a Lanczos iteration is already the eigenvector of the matrix in problem, causing the zero norm of vector in a iteration and may result in some divide by zero operations later.  
  
We should optimize the workflow to avoid such a situation.

**Comment by j9263178** [comment]
Similar issue should also occur when using `Lanczos_ER`, although in that case no Lapack error is observed so far but it may cause some numerical instability.

**Comment by jeffry1829** [comment]
c3525255e9235be5fb72fa8447e9feeec880f33b

**Comment by ianmccul** [comment]
Opened #903 as a follow-up because the current `Lanczos_Gnd_Ut` code still appears to have the same class of failure mode described here.

In particular, the implementation can divide by the initial Lanczos residual norm before checking for zero/happy breakdown, and it catches `Tridiag` failures but then can continue with invalid or missing eigensolver output. The related numerical-audit issue for other Krylov routines is #900.

Opened by Codex on behalf of @ianmccul.
