### ISSUE TITLE
Benchmark by DMRG

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#44]
We need to benchmark the speed of DMRG with ITensor or TeNPy. The implementation of DMRG may also affect the benchmark, and the implementation may depends on the API of tensor contraction, so I would not put this in high priority for now. However it is useful to have a quick comparison to see roughly how efficient Cytnx compare to others. As Ke suggested, we can make a figure similarly to which in

https://itensor.github.io/ITensorBenchmarks.jl/dev/tenpy_itensor/index.html

**Comment by j9263178** [comment]
<img width="762" alt="螢幕快照 2022-04-17 下午6 04 21" src="https://user-images.githubusercontent.com/54367491/163710938-fd0a67b9-96f8-4ba4-8b17-d7fce84abb87.png">

Here is a preliminary comparison between single thread Itesnor and Cytnx DMRG, with the common settings Nsites=32, numsweeps=8 and svd_cutoff_error = 0 (for growing to arbitary large bondim), the task is XX model with U(1) symmetry.

The result means that we should further optimize the U(1) DMRG so that it could outperform dense case in small D, one short-term solution is to do the contiguous tasks before we throw all the tensors into the iterative solver (if we assume the contiguous() part is causing trouble). Dense DMRG is also slow compare to Itensor, we should also investigate how to optimize it.

For the parameters of the iterative solver, in this benchmark the cytnx DMRG uses Lanczos_Gnd_Ut with maxit=2 while in Itensor they use Davidson with niter =2.
