### ISSUE TITLE
[Optimization] Overhead of checking the bond structure in contraction

### ISSUE THREAD

**Issue by chiamin** [kaihsin/Cytnx#53]
I remember that Cytnx will check the dimension (and the quantum number?) of the bonds when doing the contraction. Can we benchmark how much time this checking take? If the overhead is small, it might worth to always turn on the check. In any case we should make an option to turn it on/off. Do we already have it?

**Comment by j9263178** [comment]
The checking task should be a "number of contracted bonds" times "average number of QNs in each bonds" complexity (line 1503 in SparseUniTensor.cpp), which didn't show noticeable effect in my dmrg env-MPSsite contraction profiling since this is roughly O(D) and reshape() or matmul() will dominate.

I didn't see the options to turn these checkings off.

**Comment by kaihsin** [comment]
A quick comment. If the dimension of two Bonds that compares does not match, the complexity is O(1).

**Comment by kaihsin** [comment]
72bdc4 add a global variable User_debug. Need to modify the Qnum checking part inside this switch.
