### ISSUE TITLE
UniTensor Trace is too slow

### ISSUE THREAD

**Issue by TCC0731** [kaihsin/Cytnx#73]
UniTensor Trace is too slow.

![image](https://user-images.githubusercontent.com/65670274/167399444-50cb330a-ce54-40d6-86df-8df4d2fb694e.png)

**Comment by jeffry1829** [comment]
Hi, you may use single thread by putting `OMP_NUM_THREADS=1` in front of `python run.py` to solve this temporary(Or simply don't use Trace).
I'm not familiar with jupyter notebook, so you may try to find way to set enviroment variable. (Note that: Methods like os.putenv() does not work)
Also, If there're some process in the machine you used for executing cytnx that [used 100% of any CPU core](https://stackoverflow.com/questions/70126350/openmp-incredibly-slow-when-another-process-is-running), this slow behavior could happen.

Also, I can't find a machine that can run cytnx, profilier and doesn't have NUMA enabled. Can anyone help profiling? 👍 
The current profiling shows enormously large spintime. And all time are wasted in __kmp_fork_barrier.
Spintime might come from the NUMA structure. 
![image](https://user-images.githubusercontent.com/6897769/167611099-294b3a2d-f49c-450f-8468-c58b232131fb.png)
![image](https://user-images.githubusercontent.com/6897769/167611147-01b109b0-71af-4853-a8fd-75ac9b4a3014.png)

[The current implementation of linalg/Trace.cpp](https://github.com/kaihsin/Cytnx/blob/master/src/linalg/Trace.cpp#L103) may cost too much time spawning threads.
I tried moving `#pargma omp parallel` to the outer for loop, and add some `#pragma omp single` and `#pragma omp for` to maintain the same behavior. 
![image](https://user-images.githubusercontent.com/6897769/167608201-269dcaf6-8b6c-4cc5-9942-89763c674cee.png)
![image](https://user-images.githubusercontent.com/6897769/167608355-ace7b6e4-ded7-48f3-ac8d-026fedcc2bda.png)

The huge difference between the two execution time may be due to the way vtune profiles(generating many threads may cost a lot in vtune Hotspot profiling I guess), in the normal execution, there's no so much difference(while single thread almost finish it instantly.)

As someone I know suggests, seems like we shouldn't use parallel computing for such simple code block? The cost for context switching etc. may be bigger than the real task we are dealing with? I'm not sure how to deal with parallelism, I guess we may need more investigation and discussion?

The code I'm using to profile can be found [here](https://github.com/jeffry1829/cytnx_self/blob/b58757a2b727d0374e45f92679806eba106d36e1/tracetest/tracetest.cpp). (The modification to Trace.cpp are lost)
