### ISSUE TITLE
boost-cmake

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#84]
I would like to propose to use this package: [boost-cmake](https://github.com/ORNL-QCI/boost-cmake) from *Oak Ridge National Laboratory Quantum Computing Institute* for easier/better boost integration.

Some advantages:
````
Boost will automatically be downloaded from GitHub as a minified archive created with the repack.sh script.
````
and
````
Using this, as long as your main project is configured properly, Boost will be built with the same compiler, same architectures (in case of universal macOS or iOS build), same compilation flags (think of Clang sanitizers for example) without any hassle.
````

**Comment by j9263178** [comment]
I tried adding it as submodule and it works well fetching and linking boosts when building the cytnx. The python API works fine, but it turns out that when user wants to compile their c++ project that includes cytnx they still need the boost installed in their system and it might be confusing, we should have more discussion to figure out if it is more compact to 'not' add this boost-cmake and let users take care of boost themselves.
