### ISSUE TITLE
Ubuntu 20.04.4 LTS@WSL conda install fails

### ISSUE THREAD

**Issue by pcchen** [kaihsin/Cytnx#89]
OS: Ubuntu 20.04.4 LTS@WSL
````
conda install -c kaihsinwu cytnx
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - cytnx -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
````

**Comment by jeffry1829** [comment]
Hi, since I can't reproduce it now. Would you please provide the following informations?
1. `strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_`
2. `conda list`
3. If the python version is not 3.9, try using 3.9?
4. Try using mamba as 

> Conda's Conflict Reporting is Not Helpful

stated in https://stackoverflow.com/questions/62288835/how-to-interpret-conda-package-conflicts/69137255#69137255

By the way, I really suspect there's something to do with wsl2 since I had encounter problems of `glibc 2.17 not found` in WSL2 before, and the problem disappear magically. However I couldn't find any related issue in wsl repository. 

Thank you!
